import type { Metadata } from "next";
import "styles/globals.css";
import Header from "./components/Header/Header";

import localFont from 'next/font/local';

const satoshiFont = localFont({
  src: "./fonts/Satoshi-Variable.woff2",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${satoshiFont.className}`}>
      <body>
        <Header />


        <div>
          {children}
        </div>
        <footer>
          footer
        </footer>
      </body>

    </html>
  );
}
